/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Farhan Nasir
 */
public class detailspanel extends javax.swing.JPanel {

    /**
     * Creates new form detailspanel
     */
    String st_sender, st_receiver, st_email, st_amount;

    public detailspanel() {
        st_sender = "";
        st_receiver = "";
        st_email = "";
        st_amount = "";
        initComponents();
    }

    public detailspanel(String sen, String rec, String ema, String amo) {
        st_sender = sen;
        st_receiver = rec;
        st_email = ema;
        st_amount = amo;
        initComponents();
        sendname.setText(sen);
        receivename.setText(rec);
        receiveemail.setText(ema);
        amount.setText(amo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        history = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        receivename = new javax.swing.JTextField();
        sendname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        receiveemail = new javax.swing.JTextField();
        generate = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 75, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(233, 29, 61));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(245, 75, 100));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Receive Salami");
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 40));

        jPanel5.setBackground(new java.awt.Color(245, 75, 100));
        jPanel5.setLayout(new java.awt.BorderLayout());

        history.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history.setText("History");
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });
        jPanel5.add(history, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 40));

        jPanel6.setBackground(new java.awt.Color(245, 75, 100));

        logout.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 400));

        jPanel2.setBackground(new java.awt.Color(36, 42, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Receive Salami");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 40));
        jPanel2.add(receivename, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 350, -1));

        sendname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendnameActionPerformed(evt);
            }
        });
        jPanel2.add(sendname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 350, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Receiver:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sender:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Receiver's Email:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 20));
        jPanel2.add(receiveemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 350, -1));

        generate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generate.setText("Generate Receipt");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        jPanel2.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 350, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Amount:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 550, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void sendnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendnameActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:

        st_sender = sendname.getText();
        st_receiver = receiveemail.getText();
        st_email = receiveemail.getText();
        st_amount = amount.getText();

        setVisible(false);
        logoutpanel lgp = new logoutpanel(st_sender, st_receiver, st_email, st_amount);
        getParent().add(lgp);
        lgp.setVisible(true);
        JFrame frame = new JFrame();
        int n = JOptionPane.showConfirmDialog(frame, "Would you like to Logout?", "Logout", JOptionPane.YES_NO_OPTION);
        //System.out.println(n);
        if (n == 0) {
            lgp.setVisible(false);
            loginpanel lp = new loginpanel();
            getParent().add(lp);
            lp.setVisible(true);
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
        // TODO add your handling code here:
        st_sender = sendname.getText();
        st_receiver = receiveemail.getText();
        st_email = receiveemail.getText();
        st_amount = amount.getText();
        System.out.println(st_sender + "   ssc");

        setVisible(false);
        historypanel hp = new historypanel(st_sender, st_receiver, st_email, st_amount);
        getParent().add(hp);
        hp.setVisible(true);
    }//GEN-LAST:event_historyMouseClicked

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        String sender = sendname.getText();
        String receiver = "Farhan Nasif Nizami";
        if (!receivename.getText().equals("")) {
            receiver = receivename.getText();
            //System.out.println(receiver);
        }
        String receivermail = receiveemail.getText();
        String amountString = amount.getText();
        System.out.println(sender+ " "+ amountString + "   f");
        if (!sender.equals("") && !amountString.equals("")) {
            File f = new File("salami.csv");

            try {
                FileWriter fw = new FileWriter(f, true);
                fw.write(sender + "," + receiver + "," + receivermail + "," + amountString + "\n");
                fw.flush();
                fw.close();

                File fl = new File("D:\\MIST\\Salami Collection Receipt\\" + sender + ".txt");

                FileWriter fq = new FileWriter(fl, true);

                String receipt = "\t\tSalami Collection Receipt\n"
                        + "\tঈদ আনন্দ ঘরে ঘরে, সালামি দিন দুহাত ভরে\n"
                        + "\n"
                        + "\n"
                        + "Date: 8 May, 2022\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\tReceived from: " + sender + "\n"
                        + "\tAmount Received: " + amountString + " Taka\n"
                        + "\tReceived By: " + receiver + "\n"
                        + "\tPurpose: Eid Salami\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "\n"
                        + "Note: Salami received through the app is not refundable.\n"
                        + "\n"
                        + "";

                fq.write(receipt);
                fq.flush();
                fq.close();

                JFrame msg = new JFrame();
                JOptionPane.showMessageDialog(msg, "Imformation inserted successfully");

                sendname.setText("");
                receivename.setText("");
                receiveemail.setText("");
                amount.setText("");

            } catch (IOException ex) {
                Logger.getLogger(detailspanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_generateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton generate;
    private javax.swing.JLabel history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField receiveemail;
    private javax.swing.JTextField receivename;
    private javax.swing.JTextField sendname;
    // End of variables declaration//GEN-END:variables
}
