/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

/**
 *
 * @author Farhan Nasir
 */
public class individual extends javax.swing.JPanel {

    /**
     * Creates new form individual
     */
    public individual() {
        initComponents();
    }
    
    public void setname(String s)
    {
        name.setText(s);
    }
    public void settaka(String s)
    {
        taka.setText(s);
    }
    public String gettaka()
    {
        return taka.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taka = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 42, 56));
        setMaximumSize(new java.awt.Dimension(550, 40));
        setMinimumSize(new java.awt.Dimension(550, 40));
        setPreferredSize(new java.awt.Dimension(550, 40));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taka.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taka.setForeground(new java.awt.Color(255, 255, 255));
        taka.setText("1000 Taka");
        add(taka, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 80, 20));

        name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("jLabel1");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 270, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel name;
    private javax.swing.JLabel taka;
    // End of variables declaration//GEN-END:variables
}
