/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

/**
 *
 * @author Farhan Nasir
 */
public class totalpanel extends javax.swing.JPanel {

    /**
     * Creates new form totalpanel
     */
    public totalpanel() {
        initComponents();
    }
    
    public void setTaka(String s)
    {
        tottaka.setText(s);
    }
    public String gettaka()
    {
        return tottaka.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tottaka = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 42, 56));
        setMaximumSize(new java.awt.Dimension(550, 40));
        setMinimumSize(new java.awt.Dimension(550, 40));
        setPreferredSize(new java.awt.Dimension(550, 40));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Total Salami");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 40));

        tottaka.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tottaka.setForeground(new java.awt.Color(255, 255, 0));
        tottaka.setText("1000 Taka");
        add(tottaka, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 80, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tottaka;
    // End of variables declaration//GEN-END:variables
}
